import Foundation
import GRDB

// MARK: - Errors

/// Errors thrown by `LocalIntegrationStorage`.
enum LocalIntegrationStorageError: LocalizedError {
    case databaseNotInitialized
    case integrationNotFound(String)

    var errorDescription: String? {
        switch self {
        case .databaseNotInitialized:
            return "LocalIntegrationStorage: database is not initialized"
        case .integrationNotFound(let id):
            return "LocalIntegrationStorage: integration not found: \(id)"
        }
    }
}

// MARK: - Kind / format enums

/// Discriminator for a `LocalIntegrationRecord`.
///
/// Stored as `TEXT` in the `local_integrations.kind` column. New cases are
/// safe to add without a schema migration — drainer-side code is expected to
/// guard against unknown raw values.
enum LocalIntegrationKind: String, Codable {
    case webhook
    case filesystem
}

/// Output format for filesystem integrations. Ignored when `kind == .webhook`.
///
/// Stored as `TEXT` in the `local_integrations.format` column.
enum LocalIntegrationFormat: String, Codable {
    case json
    case markdown
}

// MARK: - Record

/// GRDB row record mirroring the `local_integrations` table (see
/// `RewindDatabase.swift` migration `createLocalIntegrations`).
///
/// Field-for-field parity with the schema — order matches the migration so the
/// implicit Codable column mapping lines up.
///
/// INVARIANT (enforced at `create`/`update` callsites in `AddLocalAppSheet`,
/// not in the type): `kind == "webhook"` ⇒ `webhookURL != nil`;
/// `kind == "filesystem"` ⇒ `folderDisplayPath != nil && format != nil`.
/// The drainer defends against violations by mapping malformed rows to
/// `.permanentFailure` rather than crashing. Revisit as a sum-type
/// `LocalIntegrationConfig` once a third kind lands.
struct LocalIntegrationRecord: Codable, FetchableRecord, PersistableRecord, Identifiable {
    /// UUID generated by the Swift caller (not autoincrement) so outbox rows
    /// can reference it before the row is committed and so IDs are stable
    /// across exports. Defaulted to a fresh UUID at construction time.
    var id: String

    /// Display name shown in the integrations table.
    var name: String

    /// Raw value of `LocalIntegrationKind` — "webhook" or "filesystem".
    /// Stored as String for forward-compat with new kinds.
    var kind: String

    /// Toggle without deleting; outbox rows are skipped while off.
    var enabled: Bool

    /// Only populated when `kind == "webhook"`.
    var webhookURL: String?

    /// Legacy security-scoped bookmark blob. Unused by the writer (the app
    /// is non-sandboxed; `folderDisplayPath` is the I/O source of truth).
    /// Kept for back-compat with old rows; new rows write nil. The GRDB
    /// column stays so we don't need a schema migration.
    /// Drop the column in the next migration that touches this table; until
    /// then, leave it alone.
    var folderBookmark: Data?

    /// Path string for filesystem integrations. I/O source of truth — the
    /// drainer reads this and hands it to `FilesystemWriter`. Only populated
    /// when `kind == "filesystem"`.
    var folderDisplayPath: String?

    /// Raw value of `LocalIntegrationFormat` — "json" or "markdown".
    /// Only populated when `kind == "filesystem"`.
    var format: String?

    var createdAt: Date

    /// Last successful delivery — for status display.
    var lastFiredAt: Date?

    /// Last failure message — cleared on next success.
    var lastError: String?

    static let databaseTableName = "local_integrations"

    init(
        id: String = UUID().uuidString,
        name: String,
        kind: String,
        enabled: Bool = true,
        webhookURL: String? = nil,
        folderBookmark: Data? = nil,
        folderDisplayPath: String? = nil,
        format: String? = nil,
        createdAt: Date = Date(),
        lastFiredAt: Date? = nil,
        lastError: String? = nil
    ) {
        self.id = id
        self.name = name
        self.kind = kind
        self.enabled = enabled
        self.webhookURL = webhookURL
        self.folderBookmark = folderBookmark
        self.folderDisplayPath = folderDisplayPath
        self.format = format
        self.createdAt = createdAt
        self.lastFiredAt = lastFiredAt
        self.lastError = lastError
    }

    // MARK: - Convenience accessors

    /// Typed view of `kind`. Nil if the stored raw value is unrecognised.
    var kindEnum: LocalIntegrationKind? { LocalIntegrationKind(rawValue: kind) }

    /// Typed view of `format`. Nil if missing or unrecognised.
    var formatEnum: LocalIntegrationFormat? {
        guard let format else { return nil }
        return LocalIntegrationFormat(rawValue: format)
    }
}

// MARK: - LocalIntegrationStorage

/// Actor-based CRUD layer for the `local_integrations` table.
///
/// The integrations table is the *registry* of user-installed local "apps"
/// (webhook POSTs and filesystem writes) that fire on `memory_created`.
/// Actual dispatch goes through `LocalIntegrationOutboxStorage` so a slow
/// webhook or unreachable iCloud folder never blocks the memory pipeline.
///
/// Mirrors the actor-singleton shape of `PendingWorkStorage` and
/// `NoteStorage` but is simpler: no claim/ack/lease, no mutation delegate
/// (the registry is small and read on demand).
actor LocalIntegrationStorage {
    static let shared = LocalIntegrationStorage()

    private var _dbQueue: DatabasePool?

    private init() {}

    // MARK: - Cache management

    /// Drop the cached DB queue (called on user switch / sign-out).
    func invalidateCache() {
        _dbQueue = nil
    }

    private func ensureInitialized() async throws -> DatabasePool {
        if let q = _dbQueue { return q }
        do {
            try await RewindDatabase.shared.initialize()
        } catch {
            log("LocalIntegrationStorage: DB init failed: \(error.localizedDescription)")
            throw error
        }
        guard let q = await RewindDatabase.shared.getDatabaseQueue() else {
            throw LocalIntegrationStorageError.databaseNotInitialized
        }
        _dbQueue = q
        return q
    }

    // MARK: - Create / update / delete

    /// Insert a new integration row. The caller may pass a freshly-constructed
    /// record with the default UUID and `Date()` timestamps; both are honoured
    /// as-is so the resulting `id` is stable and known to the caller.
    @discardableResult
    func create(_ record: LocalIntegrationRecord) async throws -> LocalIntegrationRecord {
        let db = try await ensureInitialized()
        let inserted = try await db.write { database in
            try record.inserted(database)
        }
        log("LocalIntegrationStorage: created \(inserted.kind) integration id=\(inserted.id) name=\(inserted.name)")
        return inserted
    }

    /// Full row update. Caller is responsible for preserving fields that
    /// shouldn't change (e.g. `createdAt`).
    func update(_ record: LocalIntegrationRecord) async throws {
        let db = try await ensureInitialized()
        try await db.write { database in
            try record.update(database)
        }
        log("LocalIntegrationStorage: updated id=\(record.id)")
    }

    /// Delete by id. Outbox rows that reference this integration are NOT
    /// cascaded here — the drainer handles orphans via
    /// `LocalIntegrationOutboxStorage.deleteOrphans`.
    func delete(id: String) async throws {
        let db = try await ensureInitialized()
        try await db.write { database in
            try database.execute(
                sql: "DELETE FROM local_integrations WHERE id = ?",
                arguments: [id]
            )
        }
        log("LocalIntegrationStorage: deleted id=\(id)")
    }

    // MARK: - Read

    /// Fetch one integration by id. Returns nil if not found.
    func get(id: String) async throws -> LocalIntegrationRecord? {
        let db = try await ensureInitialized()
        return try await db.read { database in
            try LocalIntegrationRecord.fetchOne(database, key: id)
        }
    }

    /// All integrations (enabled or not), oldest first. Used by the settings
    /// table.
    func listAll() async throws -> [LocalIntegrationRecord] {
        let db = try await ensureInitialized()
        return try await db.read { database in
            try LocalIntegrationRecord
                .order(Column("createdAt").asc)
                .fetchAll(database)
        }
    }

    /// Only enabled integrations. Used by the dispatcher when fanning out a
    /// `memory_created` event into the outbox.
    func listEnabled() async throws -> [LocalIntegrationRecord] {
        let db = try await ensureInitialized()
        return try await db.read { database in
            try LocalIntegrationRecord
                .filter(Column("enabled") == true)
                .order(Column("createdAt").asc)
                .fetchAll(database)
        }
    }

    // MARK: - Status mutators

    /// Toggle the enabled flag.
    func setEnabled(id: String, _ enabled: Bool) async throws {
        let db = try await ensureInitialized()
        try await db.write { database in
            try database.execute(
                sql: "UPDATE local_integrations SET enabled = ? WHERE id = ?",
                arguments: [enabled, id]
            )
        }
        log("LocalIntegrationStorage: setEnabled id=\(id) -> \(enabled)")
    }

    /// Record a successful delivery: set `lastFiredAt`, clear `lastError`.
    func recordSuccess(id: String, at: Date) async throws {
        let db = try await ensureInitialized()
        try await db.write { database in
            try database.execute(
                sql: """
                    UPDATE local_integrations
                    SET lastFiredAt = ?, lastError = NULL
                    WHERE id = ?
                """,
                arguments: [at, id]
            )
        }
    }

    /// Record a failed delivery: set `lastError`. Does NOT touch
    /// `lastFiredAt` — that field reflects the last *successful* delivery.
    func recordFailure(id: String, error: String) async throws {
        let db = try await ensureInitialized()
        try await db.write { database in
            try database.execute(
                sql: "UPDATE local_integrations SET lastError = ? WHERE id = ?",
                arguments: [error, id]
            )
        }
    }
}
